apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
  - name: kafka
    image: wurstmeister/kafka
    env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka:9092"
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://0.0.0.0:9092"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    ports:
    - containerPort: 9092
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"