apiVersion: v1
kind: Pod
metadata:
  name: vintedbot-producer
  labels:
    app: vintedbot-producer
spec:
  containers:
  - name: vintedbot-producer
    image: ctrnt/vintedbot_producer:latest
    env:
    - name: KAFKA_BROKER
      value: "kafka:9092"
    - name: DB_HOST
      value: "postgres-service"
    - name: DB_PORT
      value: "5432"
    - name: DB_USER
      value: "admin"
    - name: DB_PASS
      value: "secret"
    - name: DB_NAME
      value: "mydatabase"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"