apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
  - name: zookeeper
    image: wurstmeister/zookeeper
    ports:
    - containerPort: 2181
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"